export { clearerr } from './clearerr/clearerr.ts';
export { fclose } from './fclose/fclose.ts';
export { feof } from './feof/feof.ts';
export { ferror } from './ferror/ferror.ts';
export { fgetc } from './fgetc/fgetc.ts';
export { fgetpos } from './fgetpos/fgetpos.ts';
export { fgets } from './fgets/fgets.ts';
export { fopen } from './fopen/fopen.ts';
export { fputs } from './fputs/fputs.ts';
export { freopen } from './freopen/freopen.ts';
export { fseek } from './fseek/fseek.ts';
export { getc } from './getc/getc.ts';
export { getchar } from './getchar/getchar.ts'
export { getwchar } from './getwchar/getwchar.ts'
export { perror } from './perror/perror.ts';
export { putc } from './putc/putc.ts';
export { putchar } from './putchar/putchar.ts'
export { puts } from './puts/puts.ts';
export { putwchar } from './putwchar/putwchar.ts'
export { remove } from './remove/remove.ts';
export { rename } from './rename/rename.ts';
export { rewind } from './rewind/rewind.ts';
export { setbuf } from './setbuf/setbuf.ts';
export { tmpfile } from './tmpfile/tmpfile.ts';
export { ungetc } from './ungetc/ungetc.ts';

export { NullPtr }  from './NullPtr/NullPtr.ts';
export { EOF }  from './EOF/EOF.ts';
